name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: sigetrdb
          POSTGRES_USER: sigetr
          POSTGRES_PASSWORD: sigetr123
        ports:
          - 5432:5432
      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyarchunit
      - name: Architecture tests
        run: |
          pytest tests/test_architecture.py
      - name: Lint
        run: flake8 src/ tests/
      - name: Unit tests
        run: pytest
